name: connectivity-hub/prod/westus

on:
  push:
    branches:
      - 'main'
    paths:
      - 'connectivity-hub/prod/westus/**'
  workflow_dispatch:
    inputs:
      tf-action:
        type: choice
        default: apply
        description: Apply/Destroy Infrastructure
        options: 
        - apply
        - destroy

jobs:

  infra-deploy:
    uses: briteliteimmersive/devops-automation-enablers/.github/workflows/tf-deploy.yml@main
    with:
      tf-module-version: '1.0.0'
      tf-plan-gh-env: 'transit-services-plan-prod'
      tf-apply-gh-env: 'transit-services-apply-prod'
    secrets: inherit
