name: Workflow for deploying management groups to sandbox environment

on:
  workflow_dispatch:

jobs:

  infra-deploy:
    uses: briteliteimmersive/devops-automation-enablers/.github/workflows/tf-deploy.yml@feature/tf-workflows
    with:
      gh-env: 'sandbox'
      tf-version: '1.3.0'
      tf-module-name: 'management-groups'
    secrets: inherit
