name: management-groups/sandbox

on:
  push:
    branches:
      - 'main'
    paths:
      - 'management-groups/sandbox/**'
  workflow_dispatch:
    inputs:
      tf-action:
        type: choice
        default: apply
        description: Apply/Destroy Infrastructure
        options: 
        - apply
        - destroy

jobs:

  infra-deploy:
    uses: briteliteimmersive/devops-automation-enablers/.github/workflows/tf-deploy.yml@feature/tf-workflows
    with:
      tf-apply-gh-env: 'sandbox-apply'
      tf-module-version: '1.0.0'
    secrets: inherit
