name: policies/sandbox

on:
  push:
    branches:
      - 'main'
    paths:
      - 'policies/sandbox/**'
  workflow_dispatch:
    inputs:
      tf-action:
        type: choice
        default: apply
        description: Apply/Destroy Infrastructure
        options: 
        - apply
        - destroy

jobs:

  infra-deploy:
    uses: briteliteimmersive/devops-automation-enablers/.github/workflows/tf-deploy.yml@main
    with:
      tf-module-version: '1.0.0'
      tf-plan-gh-env: 'foundations-tf-plan-sandbox'
      tf-apply-gh-env: 'foundations-tf-apply-sandbox'
    secrets: inherit
