name: subscription-base/prod/platform/transit-services-sub001/westus

on:
  push:
    branches:
      - 'main'
    paths:
      - 'subscription-base/prod/platform/transit-services-sub001/westus/**'
  workflow_dispatch:
    inputs:
      tf-action:
        type: choice
        default: apply
        description: Apply/Destroy Infrastructure
        options: 
        - apply
        - destroy

jobs:

  infra-deploy:
    uses: briteliteimmersive/devops-automation-enablers/.github/workflows/tf-deploy.yml@main
    with:
      tf-module-version: '1.1.0'
      tf-plan-gh-env: 'prod-plan'
      tf-apply-gh-env: 'prod-apply'
      tf-cli-extra-args: '-var=${{ secrets.TF_GITHUB_PROVIDER_TOKEN }}'
    secrets: inherit
